"use client";
// import type { Metadata } from "next";
// import localFont from "next/font/local";

import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/js/bootstrap.bundle.min.js";
import "./globals.css";
import { toggleTheme, useAppStore } from "@/store/appStore";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { theme } = useAppStore()

return (
  <html lang="en">
    <body className={`${theme}-theme`}>    
      <section className={`container-full vh-100`}>
        <div className="text-end">
          <button
            type="button"
            aria-label={`Toggle theme to ${theme === "dark" ? "light" : "dark"}`}
            className={`btn btn-${theme}`}
            onClick={toggleTheme}
          >
            <i className={`bi bi-${theme === "dark" ? "sun" : "moon"}`}></i>
          </button>
        </div>
        {children}
      </section>
    </body>
  </html>
  );
}
